language: ruby
cache: bundler

rvm:
 #- "1.8.7"
 #- "1.9.2"
 #- "1.9.3"
 - "2.2.2"
 #- rbx
 
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake cucumber
  - bundle exec rspec

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
