language: ruby
cache: bundler
before_install: gem install bundler --version '1.3.5'
bundler_args: --without production
rvm:
 #- "1.8.7"
 #- "1.9.2"
 #- "1.9.3"
 - "2.2.2"
 - rbx

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
